name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest
